POST http://localhost:3002/auth/login
Content-Type: application/json
{
  "identifier": "admin@gmail.com",
  "password": "Default$123",
  "channel": "EMAIL"
}



GET http://localhost:3002/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImlzVmVyaWZpZWQiOmZhbHNlLCJmdWxsTmFtZSI6IlN5c3RlbSBBZG1pbmlzdHJhdG9yIiwicGhvbmVOdW1iZXIiOiIwODA5OTg3NjU0MyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NzkxNTk3OSwiZXhwIjoxNzc3OTE2ODc5fQ.pyBAYR2renlxEYsnlmeh_dQEYXGlvtkAvuRsxwY9MnQ


GET http://localhost:3002/admin/artisans/pending



PATCH http://localhost:3002/admin/artisans/9/approve
Authorization: Bearer 


PATCH http://localhost:3002/admin/artisans/9/reject
Authorization: Bearer 
Content-Type: application/json
{
  "reason": "i don't like you dan shehu"
}