
POST http://localhost:3002/auth/request-otp
Content-Type: application/json

{
  "identifier": "imamu@gmail.com",
  "channel": "EMAIL",
  "role": "ARTISAN"
}


POST http://localhost:3002/auth/verify-otp
Content-Type: application/json
{
  "identifier": "imamu@gmail.com",
  "otp": "325320",
  "channel": "EMAIL",
  "role": "ARTISAN"
}


POST http://localhost:3002/auth/complete-registration
Content-Type: application/json
{
  "fullName": "Usman Imam",
  "phoneNumber": "+2347053028914",
  "email": "imamu@gmail.com",
  "password": "Default$1234",
  "confirmPassword": "Default$1234",
  "role": "ARTISAN",
  "tempToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiaW1hbXVAZ21haWwuY29tIiwiY2hhbm5lbCI6IkVNQUlMIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NzE0MTc1MTAsImV4cCI6MTc3MTQxODExMH0.XrERpCwbYWdJA8Lq-DLQPfIPPOnThaDnZDApjjLvenQ"
}


POST http://localhost:3002/auth/login
Content-Type: application/json
{
  "identifier": "imamu@gmail.com",
  "password": "Default$1234",
  "channel": "EMAIL"
}

POST http://localhost:3002/auth/logout
Authorization: Bearer 

POST http://localhost:3002/auth/forgot-password
Content-Type: application/json
{
    "identifier": "synapgrid@gmail.com",
    "channel": "EMAIL"
}

POST http://localhost:3002/auth/verify-reset-otp
Content-Type: application/json
{
    "identifier": "synapgrid@gmail.com",
    "otp": "666484",
    "channel": "EMAIL"
}

POST http://localhost:3002/auth/reset-password
Content-Type: application/json
{
    "tempToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoic3luYXBncmlkQGdtYWlsLmNvbSIsImNoYW5uZWwiOiJFTUFJTCIsInR5cGUiOiJQQVNTV09SRF9SRVNFVCIsImlhdCI6MTc3MTI1NzE3OCwiZXhwIjoxNzcxMjU3Nzc4fQ.3vc8j61n5xG-AdP8gpmcpLa2XTN75a4gk0ZJhkzZ6NE",
    "newPassword": "Default$123",
    "confirmPassword": "Default$123"
}

