
POST http://localhost:3002/auth/request-otp
Content-Type: application/json

{
  "identifier": "isahgee@gmail.com",
  "channel": "EMAIL",
  "role": "USER"
}


POST http://localhost:3002/auth/verify-otp
Content-Type: application/json
{
  "identifier": "isahgee@gmail.com",
  "otp": "232516",
  "channel": "EMAIL",
  "role": "USER"
}


POST http://localhost:3002/auth/complete-registration
Content-Type: application/json
{
  "fullName": "Isah Aligee",
  "phoneNumber": "+2348178090940",
  "email": "isahgee@gmail.com",
  "password": "Default$1234",
  "confirmPassword": "Default$1234",
  "role": "USER",
  "tempToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiaXNhaGdlZUBnbWFpbC5jb20iLCJjaGFubmVsIjoiRU1BSUwiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc3ODA2Njg2NiwiZXhwIjoxNzc4MDY3NDY2fQ.ar3eYgj3CXZAjs5fbO8L822i4JvwoKZP9DApI7sDYD8"
}


POST http://localhost:3002/auth/login
Content-Type: application/json
{
  "identifier": "Martina@gmail.com",
  "password": "Default$1234",
  "channel": "EMAIL"
}

POST http://localhost:3002/auth/logout
Authorization: Bearer 

POST http://localhost:3002/auth/forgot-password
Content-Type: application/json
{
    "identifier": "synapgrid@gmail.com",
    "channel": "EMAIL"
}

POST http://localhost:3002/auth/verify-reset-otp
Content-Type: application/json
{
    "identifier": "synapgrid@gmail.com",
    "otp": "666484",
    "channel": "EMAIL"
}

POST http://localhost:3002/auth/reset-password
Content-Type: application/json
{
    "tempToken": "",
    "newPassword": "Default$123",
    "confirmPassword": "Default$123"
}

// {
//   "identifier": "admin@gmail.com",
//   "password": "Default$123",
//   "channel": "EMAIL"
// }