
POST http://localhost:3002/auth/request-otp
Content-Type: application/json

{
  "identifier": "merlik-gh@kadArtisan.com",
  "channel": "EMAIL",
  "role": "ARTISAN"
}


POST http://localhost:3002/auth/verify-otp
Content-Type: application/json
{
  "identifier": "merlik-gh@kadArtisan.com",
  "otp": "387721",
  "channel": "EMAIL",
  "role": "ARTISAN"
}


POST http://localhost:3002/auth/complete-registration
Content-Type: application/json
{
  "fullName": "Merlik Ghana",
  "phoneNumber": "+234-9057-2019",
  "email": "merlik-gh@kadArtisan.com",
  "password": "Default$123",
  "confirmPassword": "Default$123",
  "role": "ARTISAN",
  "tempToken": ""
}


POST http://localhost:3002/auth/login
Content-Type: application/json
{
  "identifier": "reecejames@kadArtisan.com",
  "password": "Default$1234",
  "channel": "EMAIL"
}

POST http://localhost:3002/auth/logout
Authorization: Bearer 

POST http://localhost:3002/auth/forgot-password
Content-Type: application/json
{
    "identifier": "joaopedro@kadArtisan.com",
    "channel": "EMAIL"
}

POST http://localhost:3002/auth/verify-reset-otp
Content-Type: application/json
{
    "identifier": "joaopedro@kadArtisan.com",
    "otp": "809002",
    "channel": "EMAIL"
}

POST http://localhost:3002/auth/reset-password
Content-Type: application/json
{
    "tempToken": "",
    "newPassword": "Default$1234",
    "confirmPassword": "Default$1234"
}
