

GET http://localhost:3002/user/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZDRlZWY4ZS0xZDgwLTQ2ZGYtODYyNy1jMGQ4Y2FlZWRkNGYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc3ODQwOTY1OCwiZXhwIjoxNzc4NDEwNTU4fQ.2GaLCoUS8eTNp0vWzTDbTgy8x6Cich7LMxtXhHG1TEY