

GET http://localhost:3002/user/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNDE0M2RlYi1lMDc2LTRkNGQtYWU5MC0zNzk4MzY4ZjNkOGYiLCJpc1ZlcmlmaWVkIjp0cnVlLCJmdWxsTmFtZSI6IkthZEFydGlzYW4gQWRtaW4iLCJwaG9uZU51bWJlciI6IisyMzQ4MDAwMDAwMDAwIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzc4NDA4MTM0LCJleHAiOjE3Nzg0MDkwMzR9.2zWzVNmWTJh-yfJ67ELYpP0C-vnrYUYlYCTFagNEAtU